version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  langfuse:
    image: langfuse/langfuse:latest
    depends_on: [postgres]
    environment:
      DATABASE_URL: postgres://langfuse:langfuse@postgres:5432/langfuse
      NEXTAUTH_SECRET: "replace-with-random-secret"
      NEXTAUTH_URL: "http://localhost:3000"
      ENCRYPTION_KEY: "replace-with-32-bytes-base64"  # 32바이트 키 권장
      # 이메일 인증 비활성화(테스트 편의). 필요시 SMTP 설정으로 교체
      NEXT_PUBLIC_SIGNUP_DISABLED: "false"
      TELEMETRY_ENABLED: "false"
    ports:
      - "3000:3000"
volumes:
  pgdata:
